server:
  port: 6680
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    admin:
      jdbc-url: jdbc:mysql://47.105.194.152:3306/pp_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: pp123456

    log:
      jdbc-url: jdbc:mysql://47.105.194.152:3306/log-center?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: pp123456

    filters: stat
    maxActive: 20
    maxIdle: 10
    maxWait: 10000
    minIdle: 1
    initialSize: 1
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.qpp.admin.entity.**
  check-config-location: true

swagger:
  enabled: true

# PageHelperConfig 可以替代此方案
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  path: d:/
  #file: my.log
  level:
    com.qpp.admin.mapper: DEBUG