server:
  port: 6680
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    admin:
      jdbc-url: jdbc:mysql://47.105.194.152:3306/pp_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: pp123456

    log:
      jdbc-url: jdbc:mysql://47.105.194.152:3306/log-center?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: pp123456

    filters: stat
    maxActive: 20
    maxIdle: 10
    maxWait: 10000
    minIdle: 1
    initialSize: 1
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.qpp.admin.entity.**
  check-config-location: true

swagger:
  enabled: true

# PageHelperConfig 可以替代此方案
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  path: d:/
  #file: my.log
  level:
    com.qpp.admin.mapper: DEBUG
eureka:
  client:
      serviceUrl:
        defaultZone:  http://127.0.0.1:1111/eureka #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
 #     instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${randomServerPort.value[7000,7005]}}  #随机端口
      #instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
      lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
      lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
      status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/document.html #固定端口
 #       status-page-url: http://${spring.cloud.client.ip-address}:${randomServerPort.value[7000,7005]}/document.html #随机端口
feign:
  hystrix:
    enabled: true